# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [2]:
# Your code goes here

In [3]:
import pandas as pd
import pandas as pd

In [4]:
customer_data_1 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")
customer_data_2 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv")
customer_data_3 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv")

customer_data_1.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [5]:
customer_data_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   object
 1   ST                         1071 non-null   object
 2   GENDER                     954 non-null    object
 3   Education                  1071 non-null   object
 4   Customer Lifetime Value    1068 non-null   object
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   object
 8   Policy Type                1071 non-null   object
 9   Vehicle Class              1071 non-null   object
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

In [6]:
customer_data_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   996 non-null    object
 1   ST                         996 non-null    object
 2   GENDER                     991 non-null    object
 3   Education                  996 non-null    object
 4   Customer Lifetime Value    992 non-null    object
 5   Income                     996 non-null    int64
 6   Monthly Premium Auto       996 non-null    int64
 7   Number of Open Complaints  996 non-null    object
 8   Total Claim Amount         996 non-null    float64
 9   Policy Type                996 non-null    object
 10  Vehicle Class              996 non-null    object
dtypes: float64(1), int64(2), object(8)
memory usage: 85.7+ KB

In [7]:
customer_data_3 = customer_data_3.rename(columns={
    "State":"ST",
    "Gender":"GENDER"
})

In [8]:
customer_data_1["Customer Lifetime Value"] =customer_data_1["Customer Lifetime Value"].str.replace("%", "")
customer_data_2["Customer Lifetime Value"] =customer_data_2["Customer Lifetime Value"].str.replace("%", "")

In [9]:
customer_data_1["Number of Open Complaints"] = (
    customer_data_1["Number of Open Complaints"]
    .str.split("/")
    .str[1]
)
customer_data_1["Number of Open Complaints"].unique()

array(['0', '2', '1', '3', '5', '4', nan], dtype=object)

In [10]:
customer_data_2["Number of Open Complaints"] = (
    customer_data_2["Number of Open Complaints"]
    .str.split("/")
    .str[1]
)
customer_data_2["Number of Open Complaints"].unique()

array(['0', '1', '3', '5', '2', '4'], dtype=object)

In [11]:
customer_data_2["Number of Open Complaints"] = customer_data_2["Number of Open Complaints"].astype("Int64")
customer_data_1["Number of Open Complaints"] = customer_data_1["Number of Open Complaints"].astype("Int64")

In [12]:
customer_data_df = pd.concat([customer_data_1, customer_data_2, customer_data_3], axis = 0, ignore_index = True, join="outer")
customer_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12074 entries, 0 to 12073
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   9137 non-null   object
 1   ST                         9137 non-null   object
 2   GENDER                     9015 non-null   object
 3   Education                  9137 non-null   object
 4   Customer Lifetime Value    9130 non-null   object
 5   Income                     9137 non-null   float64
 6   Monthly Premium Auto       9137 non-null   float64
 7   Number of Open Complaints  9137 non-null   Int64
 8   Policy Type                9137 non-null   object
 9   Vehicle Class              9137 non-null   object
 10  Total Claim Amount         9137 non-null   float64
dtypes: Int64(1), float64(3), object(7)
memory usage: 1.0+ MB

In [13]:
customer_data_df["Customer Lifetime Value"] = customer_data_df["Customer Lifetime Value"].astype("float64")

In [14]:
customer_data_df.isnull().sum()

Customer                     2937
ST                           2937
GENDER                       3059
Education                    2937
Customer Lifetime Value      2944
Income                       2937
Monthly Premium Auto         2937
Number of Open Complaints    2937
Policy Type                  2937
Vehicle Class                2937
Total Claim Amount           2937
dtype: int64

In [15]:
customer_data_df = customer_data_df.dropna(subset=["Customer"])
customer_data_df.isnull().sum()

Customer                       0
ST                             0
GENDER                       122
Education                      0
Customer Lifetime Value        7
Income                         0
Monthly Premium Auto           0
Number of Open Complaints      0
Policy Type                    0
Vehicle Class                  0
Total Claim Amount             0
dtype: int64

In [16]:
customer_data_df["GENDER"] = customer_data_df["GENDER"].replace({
    
    "Femal": "F",
    "female": "F",
    "Male": "M"
})
customer_data_df["GENDER"].unique()

array([nan, 'F', 'M'], dtype=object)

In [17]:
customer_data_df["GENDER"] = customer_data_df["GENDER"].ffill()

In [18]:
customer_data_df["ST"] = customer_data_df["ST"].replace({
    "AZ" : "Arizona",
    "WA" : "Washington",
    "Cali" : "California"
})
customer_data_df["ST"].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon'],
      dtype=object)

In [19]:
customer_data_df["Education"] = customer_data_df["Education"].replace({
    "Bachelors" : "Bachelor",
    "College" : "Bachelor",
    "Master" : "Graduate",
    "Doctor" : "Graduate"
})
customer_data_df["Education"].unique()

array(['Graduate', 'Bachelor', 'High School or Below'], dtype=object)

In [20]:
customer_data_df["Vehicle Class"] = customer_data_df["Vehicle Class"].replace({
    "Luxury Car": "Luxury",
    "Luxury SUV": "Luxury",
    "Sports Car": "Luxury",
})
customer_data_df["Vehicle Class"].unique()

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury'], dtype=object)

In [21]:
customer_data_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9137 entries, 0 to 12073
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   9137 non-null   object
 1   ST                         9137 non-null   object
 2   GENDER                     9136 non-null   object
 3   Education                  9137 non-null   object
 4   Customer Lifetime Value    9130 non-null   float64
 5   Income                     9137 non-null   float64
 6   Monthly Premium Auto       9137 non-null   float64
 7   Number of Open Complaints  9137 non-null   Int64
 8   Policy Type                9137 non-null   object
 9   Vehicle Class              9137 non-null   object
 10  Total Claim Amount         9137 non-null   float64
dtypes: Int64(1), float64(4), object(6)
memory usage: 865.5+ KB

In [22]:
customer_data_df = customer_data_df.drop(customer_data_df.index[0])

In [23]:
customer_data_df[customer_data_df["GENDER"].isna()]

Empty DataFrame
Columns: [Customer, ST, GENDER, Education, Customer Lifetime Value, Income, Monthly Premium Auto, Number of Open Complaints, Policy Type, Vehicle Class, Total Claim Amount]
Index: []

In [24]:
ltv_mean = customer_data_df["Customer Lifetime Value"].mean()
print(ltv_mean)

182196.3896898556

In [25]:
customer_data_df = customer_data_df.fillna({"Customer Lifetime Value": ltv_mean})

In [26]:
pd.set_option('display.float_format', '{:.2f}'.format)

In [27]:
customer_data_df.sample(15)

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
10509,MS46793,Oregon,M,Bachelor,2393.92,0.00,70.00,0,Personal Auto,Four-Door Car,425.27
11114,UY95661,California,M,Graduate,4971.73,49161.00,63.00,2,Personal Auto,Two-Door Car,171.75
4033,VC83809,California,M,Graduate,343613.43,30817.00,88.00,0,Personal Auto,Four-Door Car,91.83
4331,MZ24175,Arizona,F,Bachelor,309651.12,21604.00,79.00,0,Personal Auto,Four-Door Car,379.20
10902,KE42114,Nevada,M,Graduate,4730.36,17250.00,62.00,0,Personal Auto,Four-Door Car,175.53
8987,DW37404,California,F,Bachelor,7858.05,20532.00,67.00,0,Personal Auto,Four-Door Car,282.66
10877,OJ60800,Oregon,M,Bachelor,7930.60,75988.00,67.00,0,Personal Auto,Four-Door Car,200.55
5321,TN73558,Arizona,F,High School or Below,3731.50,0.00,96.00,0,Personal Auto,Four-Door Car,460.80
940,XI41106,Arizona,M,Bachelor,1687432.82,55390.00,71.00,0,Corporate Auto,Two-Door Car,256.27
11148,NG69817,California,F,Bachelor,7540.39,0.00,68.00,0,Personal Auto,Two-Door Car,519.76
5484,OO11531,Nevada,F,Graduate,2540.55,37125.00,63.00,0,Personal Auto,Four-Door Car,290.91
9115,MS41043,Arizona,F,Bachelor,7469.15,0.00,199.00,0,Personal Auto,Luxury,1956.37
9579,LV44800,California,F,High School or Below,3056.99,78310.00,76.00,0,Personal Auto,Four-Door Car,364.80
6368,LX24476,Oregon,F,Bachelor,3619.06,0.00,98.00,0,Personal Auto,Four-Door Car,310.84
5528,HV62406,Oregon,F,High School or Below,2482.41,26100.00,67.00,0,Personal Auto,Four-Door Car,482.40

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [28]:
# Your code goes here

In [52]:
marketing_data = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv")
marketing_data.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.22,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.80,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.53,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.92,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.92,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.00,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.44,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.01,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.07,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.93,Four-Door Car,Medsize,A,1

In [53]:
marketing_data_df = marketing_data.copy()
marketing_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   unnamed:_0                     10910 non-null  int64
 1   customer                       10910 non-null  object
 2   state                          10910 non-null  object
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10910 non-null  object
 5   coverage                       10910 non-null  object
 6   education                      10910 non-null  object
 7   effective_to_date              10910 non-null  object
 8   employmentstatus               10910 non-null  object
 9   gender                         10910 non-null  object
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  object
 12  marital_status                 10910 non-null  object
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10910 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_of_open_complaints      10910 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  object
 19  policy                         10910 non-null  object
 20  renew_offer_type               10910 non-null  object
 21  sales_channel                  10910 non-null  object
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10910 non-null  object
 24  vehicle_size                   10910 non-null  object
 25  vehicle_type                   10910 non-null  object
 26  month                          10910 non-null  int64
dtypes: float64(4), int64(6), object(17)
memory usage: 2.2+ MB

In [54]:
marketing_data["renew_offer_type"].unique()

array(['Offer3', 'Offer4', 'Offer2', 'Offer1'], dtype=object)

In [55]:
marketing_data["sales_channel"].unique()

array(['Agent', 'Call Center', 'Branch', 'Web'], dtype=object)

In [56]:
marketing_data.isnull().sum()

unnamed:_0                       0
customer                         0
state                            0
customer_lifetime_value          0
response                         0
coverage                         0
education                        0
effective_to_date                0
employmentstatus                 0
gender                           0
income                           0
location_code                    0
marital_status                   0
monthly_premium_auto             0
months_since_last_claim          0
months_since_policy_inception    0
number_of_open_complaints        0
number_of_policies               0
policy_type                      0
policy                           0
renew_offer_type                 0
sales_channel                    0
total_claim_amount               0
vehicle_class                    0
vehicle_size                     0
vehicle_type                     0
month                            0
dtype: int64

In [57]:
marketing_data_df.groupby("state").size()

state
Arizona       1937
California    4183
Nevada         993
Oregon        2909
Washington     888
dtype: int64

In [58]:
marketing_data_drop = ["policy_type", "vehicle_size", "total_claim_amount", "number_of_open_complaints", "unnamed:_0", "effective_to_date", "marital_status", "months_since_last_claim", "month", "response", "vehicle_type"]

In [59]:
marketing_data_df = marketing_data_df.drop(marketing_data_drop, axis =1)
marketing_data_df.sample(10)

,customer,state,customer_lifetime_value,coverage,education,employmentstatus,gender,income,location_code,monthly_premium_auto,months_since_policy_inception,number_of_policies,policy,renew_offer_type,sales_channel,vehicle_class
3505,QF21628,California,3095.63,Extended,High School or Below,Employed,M,53588,Suburban,77,71,1,Personal L3,Offer2,Branch,Four-Door Car
2197,QR15857,California,4330.80,Basic,College,Unemployed,F,0,Suburban,61,35,3,Personal L3,Offer3,Agent,Two-Door Car
8847,EZ48093,California,2710.81,Basic,Bachelor,Employed,M,31998,Suburban,69,70,1,Corporate L3,Offer3,Branch,Four-Door Car
9921,SY46862,Arizona,5657.69,Extended,High School or Below,Employed,M,98917,Rural,139,21,1,Corporate L1,Offer1,Agent,Sports Car
10216,TK45392,California,5107.16,Basic,Bachelor,Employed,F,35625,Urban,65,56,3,Personal L2,Offer2,Agent,Four-Door Car
9216,UP30859,Nevada,7492.06,Basic,College,Employed,F,39815,Rural,64,68,2,Special L3,Offer3,Branch,Four-Door Car
7184,FP67637,Nevada,5380.31,Basic,Bachelor,Employed,M,93818,Urban,66,25,6,Personal L3,Offer1,Agent,Four-Door Car
10196,BG15419,Nevada,14195.36,Basic,Bachelor,Employed,F,86355,Rural,118,86,2,Personal L3,Offer1,Agent,Sports Car
7185,JD71348,California,7289.30,Extended,College,Employed,M,60875,Urban,92,84,3,Personal L3,Offer1,Branch,Four-Door Car
5330,TW46585,Nevada,4767.69,Basic,Bachelor,Unemployed,M,0,Suburban,72,12,9,Corporate L1,Offer3,Call Center,Four-Door Car

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [60]:
mkt_total_income_branch = (marketing_data_df.pivot_table(
    values="income",
    index="sales_channel",
    aggfunc="sum"
    )
    .sort_values(by="income", ascending=False)
    .astype(float).round(2)
)

mkt_total_income_branch

                    income
sales_channel
Agent         152490152.00
Branch        113775608.00
Call Center    81055004.00
Web            62200103.00

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [79]:
mkt_gen_educ = marketing_data_df.pivot_table(
    values="customer_lifetime_value",
    index=["gender", "education"],
    aggfunc="mean"
).round(2)

mkt_gen_educ

                             customer_lifetime_value
gender education
F      Bachelor                              7874.27
       College                               7748.82
       Doctor                                7328.51
       High School or Below                  8675.22
       Master                                8157.05
M      Bachelor                              7703.60
       College                               8052.46
       Doctor                                7415.33
       High School or Below                  8149.69
       Master                                8168.83

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [39]:
# Your code goes here